### ISSUE TITLE
Not working in 5.5

### ISSUE THREAD

**Issue by ronnievisser** [ethanhann/Laravel-RedisStore#3]
Hi,

I have this implemented in 2 5.3 apps and was trying to add in in 1 5.5 app. in 5.5 i'm not getting this to work.

Driver [ehann-redis] is not supported.

i have created a custom service provider and registered it in the app.php config file. I have changed the redis driver to ehann-redis. as soon as i reload my app it fails with above error. It's not even reaching the serviceprovider i created and registered.

any ideas?

**Comment by ethanhann** [comment]
It sounds like like you didn't register the driver in AppServiceProvider's boot method. How to do that is in the readme.
